name: CI
 
on: push
jobs:
  build_and_test:
    permissions:
      contents: write
    name: "Build and test"
    strategy:
      matrix:
        # os: [ubuntu-24.04, windows-2025]
        # os: [windows-2025]
        os: [macos-14]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install dependencies (linux)
      run: sudo apt-get --yes install ninja-build
      if: matrix.os == 'ubuntu-22.04'

    - name: Install Ninja (windows)   
      run: choco install ninja        
      if: matrix.os == 'windows-2025'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        version: '6.9.1'

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build
      run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config Release

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Run windeployqt to gather dependencies
      if: matrix.os == 'windows-2025'
      run: |
        cp ./build/bin/Release/qt6keychain.dll D:/a/immersion/Qt/6.9.1/msvc2022_64/bin/qt6keychain.dll
        windeployqt --release --compiler-runtime --no-translations --no-system-d3d-compiler --no-opengl-sw build/Release/immersion.exe

    - name: Run windeployqt to gather dependencies and create installer
      if: matrix.os == 'macos-14'
      run: |
        macdeployqt build/Release/immersion.app
        create-dmg build/Release/immersion.dmg build/Release/ --overwrite

    - name: Download and install Inno Setup
      if: matrix.os == 'windows-2025'
      run: |
        Invoke-WebRequest -Uri https://jrsoftware.org/download.php/is.exe -OutFile is.exe
        Start-Process -FilePath .\is.exe -ArgumentList '/VERYSILENT' -Wait

    - name: Build installer with Inno Setup
      if: matrix.os == 'windows-2025'
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" inno.iss

    - name: Release
      if: matrix.os == 'windows-2025' && github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: build/installer/ImmersionSetup.exe

    - name: Release
      if: matrix.os == 'macos-14' && github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: build/Release/immersion.dmg
