name: CI
 
on: push
jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        # os: [ubuntu-24.04, windows-2025]
        os: [windows-2025]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install dependencies (linux)
      run: sudo apt-get --yes install ninja-build
      if: matrix.os == 'ubuntu-22.04'

    - name: Install Ninja (windows)   
      run: choco install ninja        
      if: matrix.os == 'windows-2025'

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.3.0
      with:
        version: '6.9.1'

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build
      run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config Release

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    # - name: Run windeployqt to gather dependencies
    #   if: matrix.os == 'windows-2025'
    #   run: |
    #     $exe = "build\\Release\\immersion.exe"
    #     & "$Env:QTDIR\\bin\\windeployqt.exe" $exe

    # - name: Zip deployment folder
    #   if: matrix.os == 'windows-2025'
    #   run: |
    #     Compress-Archive -Path build\Release\* -DestinationPath build\release-package.zip

    # - name: Release
    #   if: matrix.os == 'windows-2025'
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: build/release-package.zip
    #     name: Release ${{ github.ref_name }}
    #     body: Release ${{ github.ref_name }}