name: CI
 
on: push
jobs:
  build_and_test:
    name: "Build and test"
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install dependencies (linux)
      run: sudo apt-get --yes install ninja-build
      if: matrix.os == 'ubuntu-22.04'

    - name: Install Ninja (windows)   
      run: choco install ninja        
      if: matrix.os == 'windows-2025'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.9.1'

    - uses: ilammy/msvc-dev-cmd@v1

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build
      run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config Debug